-- Blocking: one person making another invisible to them, in both directions.
--
-- Apple's guideline 1.2 requires any app carrying user-generated content to let
-- people block other users. BetSocial has public threads, comments and group
-- chat and had no way to do it.
--
-- One row per block, holding who blocked whom. The relationship is stored
-- one-way and read both ways: if either person blocked the other, neither sees
-- the other. Storing it once rather than twice means unblocking is one delete
-- and there is no second row to fall out of step.

CREATE TABLE public.block_ (
    blid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    blocker_uid bigint NOT NULL,
    blocked_uid bigint NOT NULL,

    created_at bigint NOT NULL,

    -- Blocking the same person twice is the same block, not a second one.
    CONSTRAINT block__pair_unique UNIQUE (blocker_uid, blocked_uid),

    -- Nobody blocks themselves. Left unchecked this would quietly erase the
    -- author from their own feed.
    CONSTRAINT chk_block_not_self CHECK (blocker_uid <> blocked_uid),

    -- A block is meaningless once either account is gone, and unlike a ledger
    -- entry there is nothing to preserve about it.
    CONSTRAINT block__blocker_fkey FOREIGN KEY (blocker_uid)
        REFERENCES public.user_ (uid) ON DELETE CASCADE,
    CONSTRAINT block__blocked_fkey FOREIGN KEY (blocked_uid)
        REFERENCES public.user_ (uid) ON DELETE CASCADE
);

-- The hot path is "everyone invisible to me", which reads the table from both
-- sides, so both directions are indexed. The unique constraint already covers
-- (blocker_uid, blocked_uid); this adds the reverse lookup.
CREATE INDEX idx_block_blocked ON public.block_ (blocked_uid);
