-- Reporting content, and a record of what was done about it.
--
-- The other half of Apple's guideline 1.2: alongside blocking, an app carrying
-- user-generated content has to offer a way to report content and a way for
-- offending material to be removed. Blocking is a private act by one person;
-- this is the path that reaches a moderator.
--
-- One table holds both the report and its outcome rather than splitting them.
-- A report without its decision is half a story, and every question worth
-- asking - what was reported, who by, what happened, who decided - is answered
-- by one row.

CREATE TABLE public.report_ (
    rid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reporter_uid bigint NOT NULL,

    -- THREAD, COMMENT or USER. Deliberately not a foreign key: one column
    -- cannot reference three tables, and a report has to outlive the thing it
    -- describes - a removed thread is exactly the case where the record matters
    -- most.
    target_type character varying(16) NOT NULL,
    target_id bigint NOT NULL,

    reason character varying(32) NOT NULL,

    -- What the reporter typed, if anything. Optional: a category is enough to
    -- act on and demanding an essay stops people reporting at all.
    detail text,

    created_at bigint NOT NULL,

    -- Null until a moderator decides. Three columns rather than one status, so
    -- "when", "who" and "what" are each answerable.
    resolved_at bigint,
    resolved_by bigint,
    action character varying(16),

    -- Reporting the same thing twice is the same report. This lets the client
    -- say "you have already reported this" instead of quietly stacking up
    -- duplicates that a moderator then has to read through.
    CONSTRAINT report__once_per_reporter UNIQUE (reporter_uid, target_type, target_id),

    CONSTRAINT chk_report_target_type
        CHECK (target_type IN ('THREAD', 'COMMENT', 'USER')),

    -- Either wholly unresolved or wholly resolved; never a decision with no
    -- decider, which is the state that makes an audit trail worthless.
    CONSTRAINT chk_report_resolution_complete
        CHECK ((resolved_at IS NULL AND resolved_by IS NULL AND action IS NULL)
            OR (resolved_at IS NOT NULL AND resolved_by IS NOT NULL AND action IS NOT NULL)),

    CONSTRAINT report__reporter_fkey FOREIGN KEY (reporter_uid)
        REFERENCES public.user_ (uid) ON DELETE CASCADE
);

-- The queue reads open reports oldest first; the partial index covers exactly
-- that and stays small however many reports have been dealt with.
CREATE INDEX idx_report_open ON public.report_ (created_at)
    WHERE resolved_at IS NULL;

-- Used to tell a reporter they have already reported something, and to count
-- how many people have reported the same thing.
CREATE INDEX idx_report_target ON public.report_ (target_type, target_id);
