-- Adds the decision_log table.
--
-- WHY: BetRepository.makeDecision() inserts into Decision_Log, but the table
-- does not exist in the development database. Both callers therefore fail at
-- runtime today:
--   * SuperUserController.decideApproval  (POST /superusers/approval)
--   * BetController.decideOutcome         (POST /api/bets/decide)
--
-- Columns are taken directly from that INSERT statement:
--   INSERT INTO Decision_Log (bet_id, reason, decision, decided_at, user_id)
--
-- Naming note: this table has no trailing underscore because the query does not
-- use one. It is deliberately consistent with the code rather than with the
-- surrounding table-naming convention.

CREATE TABLE IF NOT EXISTS public.decision_log (
    dlid       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id     bigint  NOT NULL,
    reason     text,
    decision   boolean NOT NULL,
    decided_at bigint  NOT NULL
                   DEFAULT (EXTRACT(epoch FROM CURRENT_TIMESTAMP) * (1000)::numeric),
    user_id    bigint  NOT NULL,
    CONSTRAINT decision_log_bet_id_fkey  FOREIGN KEY (bet_id) REFERENCES public.bet_ (bid),
    CONSTRAINT decision_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_ (uid)
);

CREATE INDEX IF NOT EXISTS dlidx_bet_id  ON public.decision_log USING btree (bet_id);
CREATE INDEX IF NOT EXISTS dlidx_user_id ON public.decision_log USING btree (user_id);
