-- The coin ledger.
--
-- A balance is not a number that gets edited. Every movement is a row here, and
-- the balance is their sum - so any figure on screen can be explained by pointing
-- at the rows that produced it. The previous arrangement had user_.balance as a
-- mutable column that nothing ever wrote, while settlement recorded payouts on
-- prediction_.amount_won and never touched it. Nobody could have answered "why is
-- my balance this number?", including the code.
--
-- Coins are whole. amount is a signed BIGINT count, negative for a debit, and
-- there is no decimal point anywhere near it. user_.balance is a `real` - a
-- 32-bit float, which cannot hold most decimal amounts exactly and is the wrong
-- type for counting anything. It is left in place, unread and unwritten, to be
-- dropped once this has been exercised.
--
-- Rows are never deleted or amended. A correction is a new row that reverses an
-- old one, which is what makes the history worth trusting - there is no
-- deleted_at here on purpose.

CREATE TABLE public.ledger_entry_ (
    leid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid bigint NOT NULL,
    amount bigint NOT NULL,
    reason character varying(32) NOT NULL,

    -- The bet a movement relates to, when it relates to one. No foreign key: a
    -- ledger row outlives whatever caused it, and a stake that was taken stays
    -- taken whether or not the bet is still around to point at.
    bid bigint,

    -- What happened, in words, captured at the time rather than looked up later.
    -- A bet can be renamed or removed; what the ledger says about a past movement
    -- should not change with it.
    description text NOT NULL,

    created_at bigint DEFAULT (EXTRACT(epoch FROM CURRENT_TIMESTAMP) * (1000)::numeric) NOT NULL,

    CONSTRAINT fk_ledger_uid FOREIGN KEY (uid) REFERENCES public.user_(uid) ON DELETE CASCADE,

    -- A movement of nothing is not a movement.
    CONSTRAINT chk_ledger_amount_nonzero CHECK (amount <> 0),

    CONSTRAINT chk_ledger_reason CHECK (reason IN (
        'OPENING_GRANT',
        'DAILY_TOPUP',
        'STAKE',
        'STAKE_REFUND',
        'WINNINGS',
        'ADJUSTMENT'
    ))
);

-- Every read is "this user's rows": the balance sums them, the history lists them
-- newest first, and the top-up asks when the last one of its kind was.
CREATE INDEX idx_ledger_uid_created ON public.ledger_entry_ (uid, created_at DESC);

-- Existing accounts get their opening grant too. Without this everybody already
-- registered would sit at zero for good, unable to stake anything, and the
-- feature would only work for people who signed up afterwards.
INSERT INTO public.ledger_entry_ (uid, amount, reason, description, created_at)
SELECT uid,
       1000,
       'OPENING_GRANT',
       'Opening grant',
       (EXTRACT(epoch FROM CURRENT_TIMESTAMP) * (1000)::numeric)::bigint
FROM public.user_
WHERE deleted_at IS NULL;
