package com.example.World.Users;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.lang.NonNull;



public record UserDTO(
        @Id
        Long uid, // Primary key, auto-generated by the database

        @NotEmpty
        @Size(max = 50)
        String user_name, // Unique username, max length of 50

        @NotEmpty
        @Email
        @Size(max = 100)
        String email, // Unique email address, validated as a proper email format

        @NotEmpty
        @Pattern(regexp = "^\\+?[1-9]\\d{1,14}$", message = "Invalid phone number format")
        String phone_number, // Phone number in international format, unique and validated

        @NonNull
        Long created_at // Timestamp of account creation (defaulted in the database)

) {
}
