spring.application.name=World

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.generate-unique-name=false
spring.datasource.name=world
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always

spring.server.error.include-message=always
spring.server.error.include-binding-errors=always

logging.level.org.springframework.security=DEBUG

spring.security.user.name=${SPRING_USER}
spring.security.user.password=${SPRING_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

